// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC79zSPmgtGa97TleXC3J5XOUFQs3heG5U',
    appId: '1:829483013432:web:9097c65de0fde4fa71ddcd',
    messagingSenderId: '829483013432',
    projectId: 'task1-e5f8a',
    authDomain: 'task1-e5f8a.firebaseapp.com',
    storageBucket: 'task1-e5f8a.appspot.com',
    measurementId: 'G-9BLZK1EBSR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrPVwauqaC5bmnd2CmdbZ1OZZiJYMCYac',
    appId: '1:829483013432:android:181e30c62c32116671ddcd',
    messagingSenderId: '829483013432',
    projectId: 'task1-e5f8a',
    storageBucket: 'task1-e5f8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRTUqwajLtY9-JddiP5AXYyB81clhumRo',
    appId: '1:829483013432:ios:1dac9f36e019edf871ddcd',
    messagingSenderId: '829483013432',
    projectId: 'task1-e5f8a',
    storageBucket: 'task1-e5f8a.appspot.com',
    iosClientId: '829483013432-t32tu6r7bbs25g4d8ekqpo3252qsvjnd.apps.googleusercontent.com',
    iosBundleId: 'com.example.task1',
  );
}
